project-apps-dev/main.tf

Resolve #206 - fix project-apps-dev state

---

project-iam/roles/ec2_instance_profile.tf

Resolves #184 - Enable devs to see container logs

---

project-iam/roles/ecs_service_role.tf

Fix #184 - service role needs permission too

---

project-iam/groups.tf
project-iam/users.tf

#216 - create group for developers

---

project-iam/users.tf

Resolve #216 - create user for @hayuna

---

project-apps-dev/GeeksAcademy/main.tf

Refactor #222 - change asg scalling to native functionality

---

project-core/bastion/locals.tf
project-core/bastion/main.tf
project-core/bastion/output.tf
project-core/bastion/sg.tf
project-core/bastion/update_ddns.sh
project-core/bastion/variables.tf
project-core/main.tf
project-core/userdata.sh

#225 - Create bastion ASG

---

project-core/bastion/variables.tf

Fix variables

---

project-apps-dev/GeeksAcademy/main.tf

Resolves #226 - move app server to private subnet

---

project-core/userdata.sh

Resolves #226 - delete userdata

---

.github/workflows/new-issue-auto-assign-org.yml

Resolves #236 - assign to org project

---

README.md

@bwieckow please look, if the update is okay, if yes, please close the PR :)
Closes #210

Closes #210

---

.github/workflows/branch-naming-rules.yml
.github/workflows/link-PR-with-issue.yml

[#234] Linking PRs with issues; [#256] enforce branch naming convention

---

.github/workflows/terraform-apply.yml
.github/workflows/terraform-plan.yml

[#258] Fix terraform apply

---

.github/workflows/terraform-apply.yml

[#258] Fix interpolation

---

project-apps-dev/userdata.sh

[#261] Fix zabbix agent config

---

modules/user/main.tf
modules/user/variables.tf
project-iam/users.tf

[#190] Enable adding multiple groups to users

---

.github/workflows/branch-naming-rules.yml

1. Update branch-naming-rules.yml
Resolves #268

[#268] Fix TOKENS

---

.github/workflows/link-PR-with-issue.yml
.github/workflows/new-issue-auto-assign-org.yml

[#268] Update new-issue-auto-assign-org.yml

---

.github/workflows/slack-project-notifier.yml

Update statuses for more events
Resolves #268

[#268] Update slack-project-notifier.yml for more events

---

project-iam/groups.tf

[#270] Enable ECS_Deployer to deploy static webpages to AWS S3 bucket

---

project-apps-dev/S3/output.tf
project-apps-dev/S3/structure_frontend.tf
project-apps-dev/main.tf

[#280] Create structure_frontend S3 bucket

---

project-apps-dev/S3/structure_frontend.tf

[#280] Feature/#280

---

project-apps-dev/cdn.tf

[#279] Create CDN for S3 structure bucket

---

project-apps-dev/cdn.tf

[#279] Missing required argument

---

project-apps-dev/cdn.tf

[#279] Missing argument

---

project-apps-dev/S3/output.tf
project-apps-dev/S3/structure.tf
project-apps-dev/cdn.tf
project-apps-dev/locals.tf
project-apps-dev/providers.tf
project-apps-dev/public_route53.tf

[#279] CDN terraformed

---

project-iam/groups.tf

[#279] Allow deployer to push to structure bucket

---

project-apps-dev/cdn.tf

[#279] Add /admin path

---

project-apps-dev/GeeksAcademy/main.tf
project-apps-dev/cdn.tf
project-apps-dev/providers.tf

[#279] Fix ordered behavior

---

project-apps-dev/cdn.tf

[#279]  Fix cdn

---

project-apps-dev/rds.tf

[#279] Skip final snapshot for RDS

---

project-apps-dev/cdn.tf

[#279] Fix origin_request_policy
